<?php if(extension_loaded('zlib')){ob_start('ob_gzhandler');} header("Content-type: text/javascript"); ?>
var PANDORA=function(){var b=!1,c={},a=(navigator.userAgent||navigator.vendor||window.opera).toLowerCase();c.mozilla=/mozilla/.test(a)&&!/webkit/.test(a);c.webkit=/webkit/.test(a);c.opera=/opera/.test(a);c.msie=/msie/.test(a)||/trident/.test(a);c.ios=a.match(/ipad/i)||a.match(/iphone/i)||a.match(/ipod/i);c.android=a.match(/android/i);a=function(){var a=document.createElement("dummy").style,b=["Webkit","Moz","O","ms","Khtml"];return function(c){var e=c.charAt(0).toUpperCase()+c.substr(1);c=(c+" "+
b.join(e+" ")+e).split(" ");var e=null,h;for(h in c)if(void 0!==a[c[h]]){e=c[h];break}return e}}();return{open:function(a){"undefined"===typeof jQuery||this.opened||jQuery("document").ready(function(b){PANDORA.$window=b(window);PANDORA.$html=b("html,body");PANDORA.$scroll=PANDORA.BROWSER.webkit?PANDORA.$window:PANDORA.$html;PANDORA.opened=!0;a(b)});return this},close:function(){b=!1;return this},isOpened:function(){return b},BROWSER:c,parseData:function(a){var b={},c,e,h,l;if(""!==a&&void 0!==a&&
null!==a)for(a=a.split(","),c=a.length,e=0;e<c;e++)h=a[e].split(":"),l=$.trim(h[0]),h=parseFloat(h[1]),b[l]=h;return b},cssfix:a,empty:function(){}}}();(function(b){b.fn.bubble=function(){return this.each(function(){var c=b(this).addClass("bubble"),a=c.attr("title");if("undefined"!==typeof a&&""!==a){var d=c.css("position"),a=b('<span class="bubble-msg">'+a+"</span>");c.attr("title","").append(a);"static"===d&&c.css("position","relative")}})}})(jQuery);
(function(){var b={},c={},a=0,d=function(){PANDORA.$window.resize(function(){for(var a in b)if("function"===typeof b[a])b[a]()}).scroll(function(){for(var a in c)if("function"===typeof c[a])c[a]()})};PANDORA.ASYNC={scroll:function(b){d();c["asyncFunction"+a]=b;++a;return this},resize:function(c){d();b["asyncFunction"+a]=c;++a;return this},clearEvents:function(){b={};c={};return this}}})();
(function(){PANDORA.SOFTLIGHT={delay:200,defaults:{x:0,y:120,z:0,scale:1,rotate:0,rotateX:0,rotateY:0,rotateZ:0,from:50,duration:400,delay:0,classSelection:"softlight"},config:function(a){this.defaults=$.extend(this.defaults,a);return this}};var b=[],c=0,a=!1,d=0,f=PANDORA.cssfix("transform"),g=PANDORA.cssfix("transition"),e=PANDORA.cssfix("perspective"),h=function(a){var b=PANDORA.$window.height(),c=a.elem.getBoundingClientRect(),c=parseInt(b-c.top);return{ready:c>=b?!0:!1,visible:c>=a.from?!0:!1}},
l=function(a){setTimeout(function(){a.elem.style.opacity="";a.elem.style[f]="";setTimeout(function(){a.elem.style[g]=""},a.duration+a.delay+50)},d)},k=function(){if(0<c){var a=[],f;for(f=d=0;f<c;f++){var e=b[f],k=h(e),g=k.ready;k.visible?(l(e),d=g?0:d+PANDORA.SOFTLIGHT.delay):a.push(e)}b=a;c=b.length}};PANDORA.SOFTLIGHT.select=function(d){PANDORA.opened&&($(("undefined"!==typeof d?d:"")+"."+PANDORA.SOFTLIGHT.defaults.classSelection).each(function(){var a=$(this).attr("data-softlight"),a=$.extend({x:PANDORA.SOFTLIGHT.defaults.x,
y:PANDORA.SOFTLIGHT.defaults.y,z:PANDORA.SOFTLIGHT.defaults.z,scale:PANDORA.SOFTLIGHT.defaults.scale,rotate:PANDORA.SOFTLIGHT.defaults.rotate,rotateX:PANDORA.SOFTLIGHT.defaults.rotateX,rotateY:PANDORA.SOFTLIGHT.defaults.rotateY,rotateZ:PANDORA.SOFTLIGHT.defaults.rotateZ,from:PANDORA.SOFTLIGHT.defaults.from,duration:PANDORA.SOFTLIGHT.defaults.duration,delay:PANDORA.SOFTLIGHT.defaults.delay},PANDORA.parseData(a));a.elem=this;if(!h(a).ready){a.from-=a.y;var d="",k=!1;0!==a.x&&(d+="translateX("+a.x+"px)");
0!==a.y&&(d+=" translateY("+a.y+"px)");0!==a.z&&(d+=" translateZ("+a.z+"px)");1!==a.scale&&(d+=" scale("+a.scale+")");0!==a.rotate?d+=" rotate("+a.rotate+"deg)":null!==e&&(0!==a.rotateX&&(d+=" rotateX("+a.rotateX+"deg)",k=!0),0!==a.rotateY&&(d+=" rotateX("+a.rotateY+"deg)",k=!0),0!==a.rotateZ&&(d+=" rotateX("+a.rotateZ+"deg)"));k&&(a.elem.parentNode.style[e]="1000px");a.elem.style.opacity="0";a.elem.style[f]=d;a.elem.style[g]="opacity "+a.duration+"ms ease-out "+a.delay+"ms, "+f+" "+a.duration+"ms ease-out "+
a.delay+"ms";b.push(a);c++}$(this).removeClass(PANDORA.SOFTLIGHT.defaults.classSelection)}),a||(PANDORA.$window.scroll(k).resize(k),a=!0),setTimeout(function(){k()},200))};PANDORA.SOFTLIGHT.forceTest=function(){k()}})();
(function(){var b=function(b){return this.init(b)};b.prototype={init:function(b){this.ready=!1;this.cfg=$.extend({imageModule:1,$image:null,$container:null},b);null!==this.cfg.$image&&null!==this.cfg.$container&&(this.ready=!0);return this.adjust()},adjust:function(b){if(this.ready){var a=parseInt(this.cfg.$container.width()),d=parseInt(this.cfg.$container.height()),f,g;a/d>=this.cfg.imageModule?(f=a,g=parseInt(a/this.cfg.imageModule),d=parseInt((d-g)/2),a="0"):(f=parseInt(this.cfg.imageModule*d),
g=d,d="0",a=parseInt((a-f)/2));this.cfg.$image.css({width:f+"px",height:g+"px",top:d+"px",left:a+"px"});"function"===typeof b&&b()}return this}};PANDORA.FIXIMAGE=function(c){return new b(c)}})();
(function(){var b=$(""),c="img-sequence",a="img-sequence-anim",d=400,f=-1,g=null,e=null,h=function(b){b.removeClass(c);setTimeout(function(){b.removeClass(a)},d+10)},l=function(){f++;if(f<b.length){var d=b.eq(f),c=d.attr("data-src");d.load(function(){h(d);"function"===typeof g&&g.apply(null,[d]);l()}).error(function(){"function"===typeof e&&e.apply(null,[d]);l()});d.attr("data-src","");d.addClass(a).attr("src",c)}};PANDORA.IMAGESEQUENCE={config:function(b){b=$.extend({classTransition:a,classSelection:c,
duration:d},b);c=b.classSelection;a=b.classTransition;d=b.duration;return this},load:function(){g=e=null;b=$("img."+c);f=-1;l();return this},success:function(a){g=a;return this},error:function(a){e=a;return this}}})();
(function(){var b=PANDORA.cssfix("transition"),c=function(a){a.style.opacity="";setTimeout(function(){a.style[b]=""},500)};PANDORA.IMAGEWAITER={select:function(a){$((a||"")+"img.wait").each(function(){var a=$(this).removeClass("wait"),f=a[0];f.style.opacity="0";f.style[b]="opacity .4s";f.complete?c(f):a.load(function(){c(this)})})}}})();
(function(){var b=!1,c=function(a,c,g){PANDORA.$html.animate({scrollTop:a+"px"},c,function(){window.location.hash=b?"":g})},a=function(a){$(a).eq(0).each(function(){var b=parseInt($(this).offset().top);c(b,1200,a)})};PANDORA.SOFTSCROLL={selectLinks:function(d){$((d||"")+"a").click(function(d){var c=$(this),e=c.attr("href");0===e.indexOf("#")&&(d.preventDefault(),b=c.hasClass("no-hash")?!0:!1,a(e))})},goByHash:function(){var b=window.location.hash;PANDORA.$html.scrollTop(0);setTimeout(function(){""!==
b&&a(b)},1E3)}}})();
(function(){var b=function(b){return this.init(b)};b.prototype={init:function(b){this.$tabs=$("#"+b).addClass("tabs");this.$container=this.$tabs.find("> .tab");this.$buttonContainer=$('<div class="tab-button-container"></div>').prependTo(this.$tabs);this.button=[];var a=this;this.$container.each(function(b){var c=$(this),g=c.attr("data-tabname"),e=c.attr("data-tabtitle"),c=c.attr("data-tabclass");b=$('<div class="tab-button '+c+'" title="'+e+'" data-index="'+b+'"><span class="icon-tab"></span>'+g+
"</div>").appendTo(a.$buttonContainer).click(function(){var b=$(this).attr("data-index");a.change(b)});a.button.push(b)});this.change(0);$(".tab-button").bubble();return this},change:function(b){this.$container.removeClass("current").eq(b).addClass("current");for(var a=this.button.length,d=0;d<a;d++)this.button[d].removeClass("current");this.button[b].addClass("current");return this}};PANDORA.TABS=function(c){return new b(c)}})();
(function(){var b=!0,c=!1,a=window.location.host,d=window.location.href,f="undefined"!==typeof history&&"undefined"!==typeof history.pushState,g=!1,e=PANDORA.BROWSER.msie,h,l,k,n=function(){l.removeClass("hidden").addClass("to70");g?h.addClass("black"):h.removeClass("black");h.fadeIn(400,function(){b=!0})},r=function(){l.removeClass("to70").addClass("to100").addClass("hidden");h.fadeOut(400,function(){l.removeClass("to100");b=!1})},p=null,q=null,t=function(c){var g=null,h=!1,w=null,C=-1===c.indexOf("?")?
"?":"&",z=function(){window.location.href=c};if(c!==d){if(-1!==c.indexOf("#")){var A=c.split("#");c=A[0];w=A[1]}"function"===typeof q&&q();n();f&&-1!==c.indexOf(a)&&!e?(h=!1,$.ajax({url:c+C+"async=1",success:function(a){g=setInterval(function(){if(b&&!h){clearInterval(g);g=null;h=!0;PANDORA.$scroll.scrollTop(0);k.html(a);var e=$("#hidden-title").text();""===e?e=document.title:document.title=e;history.pushState(null,e,c);null!==w&&(c+="#"+w);d=c;r();"function"===typeof p&&p()}},50)},error:z})):z()}return this};
PANDORA.LOADER={init:function(){c||(h=$("#blank-dimmer"),l=$("#loader-line").addClass("to70"),k=$("#content-main"),setTimeout(function(){r()},400),c=!0);return this},setLinks:function(b){f&&$((b||"")+"a:not(.no-async)").click(function(b){var c=$(this),d=c.attr("href");-1!==d.indexOf(a)&&(b.preventDefault(),g="black"===c.attr("data-blank")?!0:!1,t(d))});return this},load:t,before:function(a){q=a;return this},success:function(a){p=a;return this}}})();
(function(){var b={facebook:{url:"https://www.facebook.com/sharer/sharer.php?u="},twitter:{url:"https://twitter.com/home?status=",descriptionSeparator:":%20",width:"635",height:"430"},google:{url:"https://plus.google.com/share?url=",width:"560",height:"580"},pinterest:{url:"https://pinterest.com/pin/create/button/?url=",width:"1000",height:"600"}};PANDORA.SHARE={setLinks:function(c){$((c||"")+"a.share").click(function(a){a.preventDefault();a=$(this);var c=$.parseJSON($.trim(a.attr("data-share").replace(/\'/g,
'"')));if(null!=c){var c=$.extend({on:"",media:"",description:""},c),f=window.location.href,g=c.on;a=$.extend({width:"600",height:"360",mediaSeparator:"&media=",descriptionSeparator:"&description=",title:"Share"},b[g]);var e=PANDORA.$window.width(),h=PANDORA.$window.height(),l=parseInt(a.width),k=parseInt(a.height);e<l+30&&(l=e-30,a.width=l);h<k+60&&(k=h-60,a.height=k);e=Math.round((e-l)/2);h=Math.round((h-k)/2);c.description=encodeURI(c.description.replace(/\|/g,"'"));switch(g){case "pinterest":c=
a.url+f+a.mediaSeparator+c.media+a.descriptionSeparator+c.description;break;case "twitter":c=a.url+c.description+a.descriptionSeparator+f;break;default:c=a.url+f}window.open(c,a.title,"width="+a.width+", height="+a.height+",left="+e+",top="+h)}})}}})();
(function(){var b=null,c={loadedApi:!1,loadedComments:!1,init:function(){var a=this;this.loadedComments=!1;this.loadedApi?a.setTabEvent():$.getScript("https://apis.google.com/js/plusone.js",function(){a.loadedApi=!0;a.setTabEvent()})},setTabEvent:function(){var a=this;b.button[1].click(function(){a.loadedComments||(a.loadComments(),a.loadedComments=!0)})},loadComments:function(){var a=$("#googleCommentsContainer").width();gapi.comments.render("googleCommentsContainer",{href:window.location,width:a,
first_party_property:"BLOGGER",view_type:"FILTERED_POSTMOD"})}};PANDORA.SOCIALCOMMENTS={set:function(a){b=PANDORA.TABS("commentTabs");setTimeout(function(){c.init()},400)}}})();
(function(){var b=null,c=function(){var a=!0;b.each(function(){var b=$(this);b.removeClass("error");var c=!0,g=b.find("input,textarea"),e=parseInt(b.attr("data-min")),h=g.val(),e=isNaN(e)?3:e;h.length<e?(c=!1,b.addClass("error"),g.focus()):b.hasClass("email")&&-1==h.search(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i)&&(c=!1,b.addClass("error"),g.focus());c||(a=!1)});return a};PANDORA.VALIDATION={set:function(a){b=$((a||"")+"fieldset.validate").removeClass("validate");$("#submit").click(function(a){c()||
a.preventDefault()});$("#clearFields").click(function(a){a.preventDefault();b.removeClass("error").find("input,textarea").val("").eq(0).focus()})}}})();
PANDORA.open(function(b){var c,a="home",d=!1,f="",g=!0,e=b("#header-main"),h={limitToHide:0,sections:"illustration illustration-post design design-post blog blog-post error404 search about-me page contact".split(" "),backColors:{illustration:!1,"illustration-post":!1,design:!0,"design-post":!0,blog:!0,search:!0,"blog-post":!0,error404:!0,"about-me":!1,page:!0,contact:!1},setResposive:function(){var a=b("#res-menu-dimmer");b("#res-menu-btn").click(function(){e.add(a).addClass("res-show")});a.add(e.find("a")).click(function(){e.add(a).removeClass("res-show")});
return this},current:function(a){b(".main-menu a").removeClass("current");b("."+a+"-menu").addClass("current");this.backColors[a]?e.addClass("white"):e.removeClass("white")},setCurrentByScroll:function(){var a=[],c,f=this.sections.length;g=!0;d&&(a.push({$e:b("#what-i-do"),name:"what-i-do"}),g=!1);for(c=0;c<f;c++){var k=b("#"+this.sections[c]);0<k.length&&a.push({$e:k,name:this.sections[c]})}var l=a.length,m="none",u,x;c=function(){x=9999999;u="";for(var b=0;b<l;b++){var c=Math.abs(a[b].$e[0].getBoundingClientRect().top);
c<x&&(x=c,u=a[b].name)}u!==m&&(h.current(u),m=u);d&&("what-i-do"===m&&g&&(e.addClass("hidden"),g=!1),"what-i-do"===m||g||(e.removeClass("hidden"),g=!0))};PANDORA.ASYNC.scroll(c).resize(c);c()}},l=function(a){a=a||4;var c;c='<svg version="1.1" xmlns="http://www.w3.org/2000/svg" class="invisible">'+('<filter id="blur"> <feGaussianBlur stdDeviation="'+a+'" /> </filter>')+'</svg><style type="text/css">';c+="img.blur { filter: url(#blur); -webkit-filter: blur("+a+"px); -moz-filter: blur("+a+"px); filter: blur("+
a+'px); filter:progid:DXImageTransform.Microsoft.Blur(PixelRadius="'+a+'"); }';c+="</style>";b("#content-main").append(c)},k=function(){for(var a=["brand","illustration","design","blog","about-me"],c=a.length,d={brand:b(".brand").attr("href")},e=1;e<c;e++){var f=a[e];d[f]=b("."+f+"-menu").attr("href")}return function(e,f){if(0==e.length){b(".brand").attr("href",d.brand);for(var g=1;g<c;g++){var h=a[g];b("."+h+"-menu").attr("href",d[h])}}else for(g=0;g<e.length;g++)h=e[g],h="brand"===h?b(".brand").attr("href",
"#content-main"):b("."+h+"-menu").attr("href","#"+h),h.removeClass("no-hash"),f&&h.addClass("no-hash")}}(),n=function(a,b,c,d){b=b||0;d=d||!1;var e=PANDORA.$window.height();d?a.css("min-height",e-b+"px"):a.height(e-b);"undefined"!==typeof c&&c(e)},r=function(a){a=b("<link rel='stylesheet' type='text/css' href='"+a+"'>");b("head").append(a)},p=function(){var a=!1;return function(){var c=b(".wipSlider");0<c.length&&(a?c.wipSlider():(r(baseTemplateURL+"/js/libs/wipslider.css"),b.getScript(baseTemplateURL+
"/js/libs/jquery.wipSlider.min.js",function(){a=!0;c.wipSlider()})))}}(),q=function(){var a=!1;return function(){var c=!1;b("pre").not(".no-print").each(function(){var a=b(this).addClass("prettyprint");a.text(a.html());c=!0});c&&(a?prettyPrint():(r(baseTemplateURL+"/js/libs/prettify.css"),b.getScript(baseTemplateURL+"/js/libs/prettify.js",function(){a=!0;prettyPrint()})))}}(),t=function(){var a=b("#gallery-menu").find(".gm-btn"),c=b(".gallery-fig"),d="all",e=!0,f=function(b,f){b!=d&&e&&(e=!1,"all"==
b?c.removeClass("hidden"):"all"==d?c.not("."+b).addClass("hidden"):(c.filter("."+d).addClass("hidden"),c.filter("."+b).removeClass("hidden")),d=b,setTimeout(function(){e=!0;PANDORA.SOFTLIGHT.forceTest()},600),a.removeClass("current"),f.addClass("current"))};a.click(function(){var a=b(this),c=a.text().toLowerCase().replace(/ /g,"-");-1!=c.indexOf("all-")&&(c="all");f(c,a)})},v={init:function(){b("#about-to-contact").show();this.$aboutMe=b("#about-me");this.$aboutMeText=b("#about-text");this.aboutMeMarginBottom=
30;this.aboutMeImgFixer=PANDORA.FIXIMAGE({imageModule:192/94,$image:b("#about-img"),$container:this.$aboutMe});k(["about-me"],!0);return this},resize:function(){var a=this;n(a.$aboutMe,a.aboutMeMarginBottom,function(b){a.aboutMeImgFixer.adjust();b=a.$aboutMeText.height()/2;a.$aboutMeText.css("margin-top","-"+b+"px")});return this},setEvent:function(){var a=this;PANDORA.ASYNC.resize(function(){a.resize()});return this}},B=function(){var a=b("#presentation"),c=b("#presentation-hand"),f=!0,h=b("#illustration"),
l=b("#blog");v.init();var m=function(){n(a,20,function(a){a=a/2-570;a=0<a?0:a;f&&-330>a&&(c.hide(),f=!1);!f&&-330<a&&(c.show(),f=!0);c.css("top",a+"px")});n(h,0,PANDORA.empty,!0);n(l,0,PANDORA.empty,!0);v.resize()};d=!0;g=!1;e.addClass("hidden");c.css("opacity","1");a.addClass("presentation-visible");b("#about-to-contact").show();m();k(["brand","illustration","design","blog","about-me"],!1);PANDORA.ASYNC.resize(m)},y=function(e){c=b("#page-data");a=c.attr("data-page");c.attr("data-menu");f=e?"#content-main ":
"";d=!1;PANDORA.SOFTLIGHT.select(f);PANDORA.IMAGEWAITER.select(f);PANDORA.LOADER.setLinks(f);PANDORA.IMAGESEQUENCE.load();k([]);b(f+".bubble").bubble();switch(a){case "home":B();break;case "illustration":k(["illustration"],!0);t();break;case "illustration-post":b(".blog-pagination-arrow a").attr("data-blank","black");PANDORA.SHARE.setLinks(f);break;case "design":k(["design"],!0);t();break;case "design-post":l();PANDORA.SHARE.setLinks(f);q();p();break;case "blog":k(["blog"],!0);break;case "blog-post":l();
PANDORA.SHARE.setLinks(f);q();PANDORA.VALIDATION.set(f);PANDORA.SOCIALCOMMENTS.set(f);p();break;case "about-me":v.init().resize().setEvent()}h.setResposive().setCurrentByScroll();PANDORA.SOFTSCROLL.selectLinks(f,70);e&&"function"===typeof ga&&ga("send","pageview",{page:window.location.pathname+window.location.search,title:document.title})};PANDORA.SOFTSCROLL.goByHash();(function(){var a=!1,c=b("#goto-top"),d=function(){var b=PANDORA.$scroll.scrollTop(),d=PANDORA.$window.height();!a&&b>d&&(c.fadeIn(260),
a=!0);a&&b<=d&&(c.fadeOut(260),a=!1)};d();PANDORA.$window.scroll(d).resize(d)})();PANDORA.LOADER.init().before(function(){PANDORA.ASYNC.clearEvents()}).success(function(){y(!0)});y(!1)});
<?php if(extension_loaded('zlib')){ob_end_flush();}?>