<?php if(extension_loaded('zlib')){ob_start('ob_gzhandler');} header("Content-type: text/javascript"); ?>
var PANDORA=function(){var c=!1,b={},a=(navigator.userAgent||navigator.vendor||window.opera).toLowerCase();b.mozilla=/mozilla/.test(a)&&!/webkit/.test(a);b.webkit=/webkit/.test(a);b.opera=/opera/.test(a);b.msie=/msie/.test(a)||/trident/.test(a);b.ios=a.match(/ipad/i)||a.match(/iphone/i)||a.match(/ipod/i);b.android=a.match(/android/i);a=function(){var a=document.createElement("dummy").style,c=["Webkit","Moz","O","ms","Khtml"];return function(b){var e=b.charAt(0).toUpperCase()+b.substr(1);b=(b+" "+
c.join(e+" ")+e).split(" ");var e=null,k;for(k in b)if(void 0!==a[b[k]]){e=b[k];break}return e}}();return{open:function(a){"undefined"===typeof jQuery||this.opened||jQuery("document").ready(function(c){PANDORA.$window=c(window);PANDORA.$html=c("html,body");PANDORA.$scroll=PANDORA.BROWSER.webkit?PANDORA.$window:PANDORA.$html;PANDORA.opened=!0;a(c)});return this},close:function(){c=!1;return this},isOpened:function(){return c},BROWSER:b,parseData:function(a){var c={},b,e,k,l;if(""!==a&&void 0!==a&&
null!==a)for(a=a.split(","),b=a.length,e=0;e<b;e++)k=a[e].split(":"),l=$.trim(k[0]),k=parseFloat(k[1]),c[l]=k;return c},cssfix:a,empty:function(){}}}();(function(c){c.fn.bubble=function(){return this.each(function(){var b=c(this).addClass("bubble"),a=b.attr("title");if("undefined"!==typeof a&&""!==a){var d=b.css("position"),a=c('<span class="bubble-msg">'+a+"</span>");b.attr("title","").append(a);"static"===d&&b.css("position","relative")}})}})(jQuery);
(function(){var c={},b={},a=0,d=function(){PANDORA.$window.resize(function(){for(var a in c)if("function"===typeof c[a])c[a]()}).scroll(function(){for(var a in b)if("function"===typeof b[a])b[a]()})};PANDORA.ASYNC={scroll:function(c){d();b["asyncFunction"+a]=c;++a;return this},resize:function(b){d();c["asyncFunction"+a]=b;++a;return this},clearEvents:function(){c={};b={};return this}}})();
(function(){PANDORA.SOFTLIGHT={delay:200,defaults:{x:0,y:120,z:0,scale:1,rotate:0,rotateX:0,rotateY:0,rotateZ:0,from:50,duration:400,delay:0,classSelection:"softlight"},config:function(a){this.defaults=$.extend(this.defaults,a);return this}};var c=[],b=0,a=!1,d=0,f=PANDORA.cssfix("transform"),g=PANDORA.cssfix("transition"),e=PANDORA.cssfix("perspective"),k=function(a){var c=PANDORA.$window.height(),b=a.elem.getBoundingClientRect(),b=parseInt(c-b.top);return{ready:b>=c?!0:!1,visible:b>=a.from?!0:!1}},
l=function(a){setTimeout(function(){a.elem.style.opacity="";a.elem.style[f]="";setTimeout(function(){a.elem.style[g]=""},a.duration+a.delay+50)},d)},h=function(){if(0<b){var a=[],f;for(f=d=0;f<b;f++){var e=c[f],h=k(e),g=h.ready;h.visible?(l(e),d=g?0:d+PANDORA.SOFTLIGHT.delay):a.push(e)}c=a;b=c.length}};PANDORA.SOFTLIGHT.select=function(d){PANDORA.opened&&($(("undefined"!==typeof d?d:"")+"."+PANDORA.SOFTLIGHT.defaults.classSelection).each(function(){var a=$(this).attr("data-softlight"),a=$.extend({x:PANDORA.SOFTLIGHT.defaults.x,
y:PANDORA.SOFTLIGHT.defaults.y,z:PANDORA.SOFTLIGHT.defaults.z,scale:PANDORA.SOFTLIGHT.defaults.scale,rotate:PANDORA.SOFTLIGHT.defaults.rotate,rotateX:PANDORA.SOFTLIGHT.defaults.rotateX,rotateY:PANDORA.SOFTLIGHT.defaults.rotateY,rotateZ:PANDORA.SOFTLIGHT.defaults.rotateZ,from:PANDORA.SOFTLIGHT.defaults.from,duration:PANDORA.SOFTLIGHT.defaults.duration,delay:PANDORA.SOFTLIGHT.defaults.delay},PANDORA.parseData(a));a.elem=this;if(!k(a).ready){a.from-=a.y;var d="",h=!1;0!==a.x&&(d+="translateX("+a.x+"px)");
0!==a.y&&(d+=" translateY("+a.y+"px)");0!==a.z&&(d+=" translateZ("+a.z+"px)");1!==a.scale&&(d+=" scale("+a.scale+")");0!==a.rotate?d+=" rotate("+a.rotate+"deg)":null!==e&&(0!==a.rotateX&&(d+=" rotateX("+a.rotateX+"deg)",h=!0),0!==a.rotateY&&(d+=" rotateX("+a.rotateY+"deg)",h=!0),0!==a.rotateZ&&(d+=" rotateX("+a.rotateZ+"deg)"));h&&(a.elem.parentNode.style[e]="1000px");a.elem.style.opacity="0";a.elem.style[f]=d;a.elem.style[g]="opacity "+a.duration+"ms ease-out "+a.delay+"ms, "+f+" "+a.duration+"ms ease-out "+
a.delay+"ms";c.push(a);b++}$(this).removeClass(PANDORA.SOFTLIGHT.defaults.classSelection)}),a||(PANDORA.$window.scroll(h).resize(h),a=!0),setTimeout(function(){h()},200))};PANDORA.SOFTLIGHT.forceTest=function(){h()}})();
(function(){var c=function(c){return this.init(c)};c.prototype={init:function(c){this.ready=!1;this.cfg=$.extend({imageModule:1,$image:null,$container:null},c);null!==this.cfg.$image&&null!==this.cfg.$container&&(this.ready=!0);return this.adjust()},adjust:function(c){if(this.ready){var a=parseInt(this.cfg.$container.width()),d=parseInt(this.cfg.$container.height()),f,g;a/d>=this.cfg.imageModule?(f=a,g=parseInt(a/this.cfg.imageModule),d=parseInt((d-g)/2),a="0"):(f=parseInt(this.cfg.imageModule*d),
g=d,d="0",a=parseInt((a-f)/2));this.cfg.$image.css({width:f+"px",height:g+"px",top:d+"px",left:a+"px"});"function"===typeof c&&c()}return this}};PANDORA.FIXIMAGE=function(b){return new c(b)}})();
(function(){var c=$(""),b="img-sequence",a="img-sequence-anim",d=400,f=-1,g=null,e=null,k=function(c){c.removeClass(b);setTimeout(function(){c.removeClass(a)},d+10)},l=function(){f++;if(f<c.length){var d=c.eq(f),b=d.attr("data-src");d.load(function(){k(d);"function"===typeof g&&g.apply(null,[d]);l()}).error(function(){"function"===typeof e&&e.apply(null,[d]);l()});d.attr("data-src","");d.addClass(a).attr("src",b)}};PANDORA.IMAGESEQUENCE={config:function(c){c=$.extend({classTransition:a,classSelection:b,
duration:d},c);b=c.classSelection;a=c.classTransition;d=c.duration;return this},load:function(){g=e=null;c=$("img."+b);f=-1;l();return this},success:function(a){g=a;return this},error:function(a){e=a;return this}}})();
(function(){var c=PANDORA.cssfix("transition"),b=function(a){a.style.opacity="";setTimeout(function(){a.style[c]=""},500)};PANDORA.IMAGEWAITER={select:function(a){$((a||"")+"img.wait").each(function(){var a=$(this).removeClass("wait"),f=a[0];f.style.opacity="0";f.style[c]="opacity .4s";f.complete?b(f):a.load(function(){b(this)})})}}})();
(function(){var c=!1,b=function(a,b,g){PANDORA.$html.animate({scrollTop:a+"px"},b,function(){window.location.hash=c?"":g})},a=function(a){$(a).eq(0).each(function(){var c=parseInt($(this).offset().top);b(c,1200,a)})};PANDORA.SOFTSCROLL={selectLinks:function(d){$((d||"")+"a").click(function(d){var b=$(this),e=b.attr("href");0===e.indexOf("#")&&(d.preventDefault(),c=b.hasClass("no-hash")?!0:!1,a(e))})},goByHash:function(){var c=window.location.hash;PANDORA.$html.scrollTop(0);setTimeout(function(){""!==
c&&a(c)},1E3)}}})();
(function(){var c=function(c){return this.init(c)};c.prototype={init:function(c){this.$tabs=$("#"+c).addClass("tabs");this.$container=this.$tabs.find("> .tab");this.$buttonContainer=$('<div class="tab-button-container"></div>').prependTo(this.$tabs);this.button=[];var a=this;this.$container.each(function(c){var b=$(this),g=b.attr("data-tabname"),e=b.attr("data-tabtitle"),b=b.attr("data-tabclass");c=$('<div class="tab-button '+b+'" title="'+e+'" data-index="'+c+'"><span class="icon-tab"></span>'+g+
"</div>").appendTo(a.$buttonContainer).click(function(){var c=$(this).attr("data-index");a.change(c)});a.button.push(c)});this.change(0);$(".tab-button").bubble();return this},change:function(c){this.$container.removeClass("current").eq(c).addClass("current");for(var a=this.button.length,d=0;d<a;d++)this.button[d].removeClass("current");this.button[c].addClass("current");return this}};PANDORA.TABS=function(b){return new c(b)}})();
(function(){var c=!0,b=!1,a=window.location.host,d=window.location.href,f="undefined"!==typeof history&&"undefined"!==typeof history.pushState,g=!1,e=PANDORA.BROWSER.msie,k=function(){return window.location.protocol+"//"+window.location.hostname+window.location.pathname},l,h,m,v,x=function(){m.removeClass("hidden").addClass("to70");g?h.addClass("black"):h.removeClass("black");h.fadeIn(400,function(){c=!0})},w=function(){m.removeClass("to70").addClass("to100").addClass("hidden");h.fadeOut(400,function(){m.removeClass("to100");
c=!1})},r=null,q=null,y=function(b,t){var B=t||!1,g=null,h=!1,z=null,n=-1===b.indexOf("?")?"?":"&",p=function(){window.location.href=b};if(b!==d){if(-1!==b.indexOf("#")){var u=b.split("#");b=u[0];z=u[1]}"function"===typeof q&&q();x();f&&-1!==b.indexOf(a)&&!e?(h=!1,$.ajax({url:b+n+"async=1",success:function(a){g=setInterval(function(){if(c&&!h){clearInterval(g);g=null;h=!0;PANDORA.$scroll.scrollTop(0);v.html(a);var t=$("#hidden-title").text();""===t?t=document.title:document.title=t;B||history.pushState({path:b},
t,b);null!==z&&(b+="#"+z);d=b;w();l=k();"function"===typeof r&&r()}},50)},error:p})):p()}return this};PANDORA.LOADER={init:function(){if(!b){l=k();var a=window.location.href,c=function(){var a=window.location.hash;return function(){var c=window.location.hash,b=k();if(c!==a&&b===l)return a=c,l=k(),!0;l=k();return!1}}();h=$("#blank-dimmer");m=$("#loader-line").addClass("to70");v=$("#content-main");setTimeout(function(){w()},400);b=!0;f&&!e&&PANDORA.$window.bind("popstate",function(b){(b=b.originalEvent.state)?
PANDORA.LOADER.load(b.path,!0):c()||(window.location.href=a)})}return this},setLinks:function(c){f&&$((c||"")+"a:not(.no-async)").click(function(c){var b=$(this),d=b.attr("href");-1!==d.indexOf(a)&&(c.preventDefault(),g="black"===b.attr("data-blank")?!0:!1,y(d))});return this},load:y,before:function(a){q=a;return this},success:function(a){r=a;return this}}})();
(function(){var c={facebook:{url:"https://www.facebook.com/sharer/sharer.php?u="},twitter:{url:"https://twitter.com/home?status=",descriptionSeparator:":%20",width:"635",height:"430"},google:{url:"https://plus.google.com/share?url=",width:"560",height:"580"},pinterest:{url:"https://pinterest.com/pin/create/button/?url=",width:"1000",height:"600"}};PANDORA.SHARE={setLinks:function(b){$((b||"")+"a.share").click(function(a){a.preventDefault();a=$(this);var b=$.parseJSON($.trim(a.attr("data-share").replace(/\'/g,
'"')));if(null!=b){var b=$.extend({on:"",media:"",description:""},b),f=window.location.href,g=b.on;a=$.extend({width:"600",height:"360",mediaSeparator:"&media=",descriptionSeparator:"&description=",title:"Share"},c[g]);var e=PANDORA.$window.width(),k=PANDORA.$window.height(),l=parseInt(a.width),h=parseInt(a.height);e<l+30&&(l=e-30,a.width=l);k<h+60&&(h=k-60,a.height=h);e=Math.round((e-l)/2);k=Math.round((k-h)/2);b.description=encodeURI(b.description.replace(/\|/g,"'"));switch(g){case "pinterest":b=
a.url+f+a.mediaSeparator+b.media+a.descriptionSeparator+b.description;break;case "twitter":b=a.url+b.description+a.descriptionSeparator+f;break;default:b=a.url+f}window.open(b,a.title,"width="+a.width+", height="+a.height+",left="+e+",top="+k)}})}}})();
(function(){var c=null,b={loadedApi:!1,loadedComments:!1,init:function(){var a=this;this.loadedComments=!1;this.loadedApi?a.setTabEvent():$.getScript("https://apis.google.com/js/plusone.js",function(){a.loadedApi=!0;a.setTabEvent()})},setTabEvent:function(){var a=this;c.button[1].click(function(){a.loadedComments||(a.loadComments(),a.loadedComments=!0)})},loadComments:function(){var a=$("#googleCommentsContainer").width();gapi.comments.render("googleCommentsContainer",{href:window.location,width:a,
first_party_property:"BLOGGER",view_type:"FILTERED_POSTMOD"})}};PANDORA.SOCIALCOMMENTS={set:function(a){c=PANDORA.TABS("commentTabs");setTimeout(function(){b.init()},400)}}})();
(function(){var c=null,b=function(){var a=!0;c.each(function(){var c=$(this);c.removeClass("error");var b=!0,g=c.find("input,textarea"),e=parseInt(c.attr("data-min")),k=g.val(),e=isNaN(e)?3:e;k.length<e?(b=!1,c.addClass("error"),g.focus()):c.hasClass("email")&&-1==k.search(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i)&&(b=!1,c.addClass("error"),g.focus());b||(a=!1)});return a};PANDORA.VALIDATION={set:function(a){c=$((a||"")+"fieldset.validate").removeClass("validate");$("#submit").click(function(a){b()||
a.preventDefault()});$("#clearFields").click(function(a){a.preventDefault();c.removeClass("error").find("input,textarea").val("").eq(0).focus()})}}})();
PANDORA.open(function(c){var b,a="home",d=!1,f="",g=!0,e=c("#header-main"),k={limitToHide:0,sections:"illustration illustration-post design design-post blog blog-post error404 search about-me page contact".split(" "),backColors:{illustration:!1,"illustration-post":!1,design:!0,"design-post":!0,blog:!0,search:!0,"blog-post":!0,error404:!0,"about-me":!1,page:!0,contact:!1},setResposive:function(){var a=c("#res-menu-dimmer");c("#res-menu-btn").click(function(){e.add(a).addClass("res-show")});a.add(e.find("a")).click(function(){e.add(a).removeClass("res-show")});
return this},current:function(a){c(".main-menu a").removeClass("current");c("."+a+"-menu").addClass("current");this.backColors[a]?e.addClass("white"):e.removeClass("white")},setCurrentByScroll:function(){var a=[],b,f=this.sections.length;g=!0;d&&(a.push({$e:c("#what-i-do"),name:"what-i-do"}),g=!1);for(b=0;b<f;b++){var h=c("#"+this.sections[b]);0<h.length&&a.push({$e:h,name:this.sections[b]})}var l=a.length,n="none",p,u;b=function(){u=9999999;p="";for(var c=0;c<l;c++){var b=Math.abs(a[c].$e[0].getBoundingClientRect().top);
b<u&&(u=b,p=a[c].name)}p!==n&&(k.current(p),n=p);d&&("what-i-do"===n&&g&&(e.addClass("hidden"),g=!1),"what-i-do"===n||g||(e.removeClass("hidden"),g=!0))};PANDORA.ASYNC.scroll(b).resize(b);b()}},l=function(a){a=a||4;var b;b='<svg version="1.1" xmlns="http://www.w3.org/2000/svg" class="invisible">'+('<filter id="blur"> <feGaussianBlur stdDeviation="'+a+'" /> </filter>')+'</svg><style type="text/css">';b+="img.blur { filter: url(#blur); -webkit-filter: blur("+a+"px); -moz-filter: blur("+a+"px); filter: blur("+
a+'px); filter:progid:DXImageTransform.Microsoft.Blur(PixelRadius="'+a+'"); }';b+="</style>";c("#content-main").append(b)},h=function(){for(var a=["brand","illustration","design","blog","about-me"],b=a.length,d={brand:c(".brand").attr("href")},e=1;e<b;e++){var f=a[e];d[f]=c("."+f+"-menu").attr("href")}return function(e,f){if(0==e.length){c(".brand").attr("href",d.brand);for(var g=1;g<b;g++){var h=a[g];c("."+h+"-menu").attr("href",d[h])}}else for(g=0;g<e.length;g++)h=e[g],h="brand"===h?c(".brand").attr("href",
"#content-main"):c("."+h+"-menu").attr("href","#"+h),h.removeClass("no-hash"),f&&h.addClass("no-hash")}}(),m=function(a,c,b,d){c=c||0;d=d||!1;var e=PANDORA.$window.height();d?a.css("min-height",e-c+"px"):a.height(e-c);"undefined"!==typeof b&&b(e)},v=function(a){a=c("<link rel='stylesheet' type='text/css' href='"+a+"'>");c("head").append(a)},x=function(){var a=!1;return function(){var b=c(".wipSlider");0<b.length&&(a?b.wipSlider():(v(baseTemplateURL+"/js/libs/wipslider.css"),c.getScript(baseTemplateURL+
"/js/libs/jquery.wipSlider.min.js",function(){a=!0;b.wipSlider()})))}}(),w=function(){var a=!1;return function(){var b=!1;c("pre").not(".no-print").each(function(){var a=c(this).addClass("prettyprint");a.text(a.html());b=!0});b&&(a?prettyPrint():(v(baseTemplateURL+"/js/libs/prettify.css"),c.getScript(baseTemplateURL+"/js/libs/prettify.js",function(){a=!0;prettyPrint()})))}}(),r=function(){var a=c("#gallery-menu").find(".gm-btn"),b=c(".gallery-fig"),d="all",e=!0,f=function(c,f){c!=d&&e&&(e=!1,"all"==
c?b.removeClass("hidden"):"all"==d?b.not("."+c).addClass("hidden"):(b.filter("."+d).addClass("hidden"),b.filter("."+c).removeClass("hidden")),d=c,setTimeout(function(){e=!0;PANDORA.SOFTLIGHT.forceTest()},600),a.removeClass("current"),f.addClass("current"))};a.click(function(){var a=c(this),b=a.text().toLowerCase().replace(/ /g,"-");-1!=b.indexOf("all-")&&(b="all");f(b,a)})},q={init:function(){c("#about-to-contact").show();this.$aboutMe=c("#about-me");this.$aboutMeText=c("#about-text");this.aboutMeMarginBottom=
30;this.aboutMeImgFixer=PANDORA.FIXIMAGE({imageModule:192/94,$image:c("#about-img"),$container:this.$aboutMe});h(["about-me"],!0);return this},resize:function(){var a=this;m(a.$aboutMe,a.aboutMeMarginBottom,function(c){a.aboutMeImgFixer.adjust();c=a.$aboutMeText.height()/2;a.$aboutMeText.css("margin-top","-"+c+"px")});return this},setEvent:function(){var a=this;PANDORA.ASYNC.resize(function(){a.resize()});return this}},y=function(){var a=c("#presentation"),b=c("#presentation-hand"),f=!0,k=c("#illustration"),
l=c("#blog");q.init();var n=function(){m(a,20,function(a){a=a/2-570;a=0<a?0:a;f&&-330>a&&(b.hide(),f=!1);!f&&-330<a&&(b.show(),f=!0);b.css("top",a+"px")});m(k,0,PANDORA.empty,!0);m(l,0,PANDORA.empty,!0);q.resize()};d=!0;g=!1;e.addClass("hidden");b.css("opacity","1");a.addClass("presentation-visible");c("#about-to-contact").show();n();h(["brand","illustration","design","blog","about-me"],!1);PANDORA.ASYNC.resize(n)},A=function(e){b=c("#page-data");a=b.attr("data-page");b.attr("data-menu");f=e?"#content-main ":
"";d=!1;PANDORA.SOFTLIGHT.select(f);PANDORA.IMAGEWAITER.select(f);PANDORA.LOADER.setLinks(f);PANDORA.IMAGESEQUENCE.load();h([]);c(f+".bubble").bubble();switch(a){case "home":y();break;case "illustration":h(["illustration"],!0);r();break;case "illustration-post":c(".blog-pagination-arrow a").attr("data-blank","black");PANDORA.SHARE.setLinks(f);break;case "design":h(["design"],!0);r();break;case "design-post":l();PANDORA.SHARE.setLinks(f);w();x();break;case "blog":h(["blog"],!0);break;case "blog-post":l();
PANDORA.SHARE.setLinks(f);w();PANDORA.VALIDATION.set(f);PANDORA.SOCIALCOMMENTS.set(f);x();break;case "about-me":q.init().resize().setEvent()}k.setResposive().setCurrentByScroll();PANDORA.SOFTSCROLL.selectLinks(f,70);e&&"function"===typeof ga&&ga("send","pageview",{page:window.location.pathname+window.location.search,title:document.title})};PANDORA.SOFTSCROLL.goByHash();(function(){var a=!1,b=c("#goto-top"),d=function(){var c=PANDORA.$scroll.scrollTop(),d=PANDORA.$window.height();!a&&c>d&&(b.fadeIn(260),
a=!0);a&&c<=d&&(b.fadeOut(260),a=!1)};d();PANDORA.$window.scroll(d).resize(d)})();PANDORA.LOADER.init().before(function(){PANDORA.ASYNC.clearEvents()}).success(function(){A(!0)});A(!1)});
<?php if(extension_loaded('zlib')){ob_end_flush();}?>